// (c) Eduardo Doria and contributors
// SPDX-License-Identifier: MIT

#ifndef MODEL_COMPONENT_H
#define MODEL_COMPONENT_H

#include "ecs/Entity.h"
#include "math/Matrix4.h"
#include <vector>
#include <map>
#include <memory>
#include <string>

namespace tinygltf {class Model;}

namespace doriax{

    struct ObjModelData;

    struct ModelSkinBinding{
        Entity mesh = NULL_ENTITY;
        std::vector<Entity> joints;
        std::vector<Matrix4> inverseBindMatrices;
    };

    struct DORIAX_API ModelComponent{
        std::shared_ptr<tinygltf::Model> gltfModel;
        std::shared_ptr<ObjModelData> objModel;

        Matrix4 inverseDerivedTransform;
        
        Entity skeleton;

        std::map<std::string, Entity> bonesNameMapping;
        std::map<int, Entity> bonesIdMapping;

        // GLTF mesh-node child entities generated by the loader and torn down on reload.
        std::map<int, Entity> meshNodesMapping;

        // Full glTF node hierarchy. Bone and mesh mappings point into these entities.
        std::map<int, Entity> nodesIdMapping;

        // Runtime bindings are rebuilt from the glTF source on load. Each skinned mesh keeps its
        // own joint order and inverse-bind matrices, so models may use more than one skin.
        std::vector<ModelSkinBinding> skinBindings;

        std::map<std::string, int> morphNameMapping;

        std::vector<Entity> animations;

        std::string filename;

        // Bake static multi-node GLTF meshes into this entity's MeshComponent instead of
        // generating one child entity per mesh node. This makes the model compatible with
        // same-entity features such as InstancedMeshComponent.
        bool mergeStaticMeshes = false;

        std::string loadedFilename;
        bool loadedMergeStaticMeshes = false;
        bool needUpdateModel = true;
    };

}

#endif //MODEL_COMPONENT_H
